# Generated by Django 5.2.7 on 2025-10-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
