# Generated by Django 5.2.7 on 2025-10-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
