# Generated by Django 5.2.7 on 2025-10-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_rename_quantity_bookings_seats_bookings_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='seats',
            new_name='seats_quantity',
        ),
    ]
