# Generated by Django 5.2.7 on 2025-10-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_rename_seats_bookings_seats_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='user_id',
            new_name='user',
        ),
    ]
