# Generated by Django 5.2.7 on 2025-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='seats',
            field=models.IntegerField(default=4),
        ),
    ]
