# Generated by Django 5.2.7 on 2025-10-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0002_trips_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='available',
            field=models.CharField(choices=[('available', 'AVAAILABLE'), ('unavailable', 'UNAVAILABLE')], default='available', max_length=60),
        ),
    ]
