# Generated by Django 5.2.7 on 2025-10-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0003_trips_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='time',
            field=models.TimeField(),
        ),
    ]
